Repository SergioJaramilloL/alamesa-server, pull requests merged in 2020-12, with the labels that each got.

#31 add method destroy for deleted document for sanitary register in coll…
  src/controllers/sanitaryRegister.controller.js
  src/routes/sanitaryRegister.js
Labels: enhancement

#32 Fix san002
  server.js
  src/controllers/client.controller.js
  src/controllers/sanitaryRegister.controller.js
  src/routes/sanitaryRegister.js
Labels: documentation

#33 delete idClient parameter from post reservation endpoint
  src/routes/reservation.js
Labels: bug

#34 Feature rsv004
  server.js
  src/controllers/companion.controller.js
  src/controllers/sanitaryRegister.controller.js
  src/models/companion.model.js
  src/models/sanitaryRegister.model.js
  src/routes/companion.js
  src/routes/sanitaryRegister.js
Labels: enhancement

#35 Fix014
  src/controllers/companion.controller.js
  src/controllers/sanitaryRegister.controller.js
  src/models/companion.model.js
  src/models/sanitaryRegister.model.js
Labels: bug

#36 add enviromental port for conect server
  server.js
Labels: bug

#37 Fix016
  src/controllers/reservation.controller.js
  src/controllers/sanitaryRegister.controller.js
  src/models/companion.model.js
  src/models/reservation.model.js
  src/models/sanitaryRegister.model.js
  src/routes/sanitaryRegister.js
Labels: enhancement

#38 fix sanitaryRegister.model
  src/models/sanitaryRegister.model.js
Labels: bug
