Repository SergioJaramilloL/alamesa-server, pull requests merged in 2021-01, with the labels that each got.

#49 Feature men003
  .gitignore
  package.json
  server.js
  src/controllers/dish.controller.js
  src/controllers/menu.controller.js
  src/models/dish.model.js
  src/models/menu.model.js
  src/models/restaurant.model.js
  src/routes/dish.js
  src/routes/menu.js
  src/utils/formData.js
  yarn.lock
Labels: Restaurant, enhancement

#50 Fix019 MVC Menu
  src/controllers/dish.controller.js
  src/controllers/menu.controller.js
  src/models/dish.model.js
  src/routes/dish.js
  src/utils/formData.js
Labels: Restaurant, bug

#52 fix the method created with only pass the id from the models
  src/controllers/reservation.controller.js
Labels: Reservation, bug

#54 Log003 recover password
  server.js
  src/controllers/email.controller.js
  src/routes/email.js
  src/utils/auth.js
  src/utils/email_templates/passRecovery.js
  src/utils/mailer.js
Labels: Authentication, Emails, enhancement

#59 Fix021 - menu restaurant
  README.md
  src/controllers/dish.controller.js
Labels: Dishes, bug

#61 fix reset password
  src/controllers/email.controller.js
  src/utils/auth.js
Labels: Emails, bug

#62 Fix022
  src/utils/email_templates/passRecovery.js
  src/utils/mailer.js
Labels: Emails, bug

#63 Img002 logo resturant profile
  src/controllers/restaurant.controller.js
  src/models/restaurant.model.js
  src/routes/dish.js
  src/routes/restaurant.js
  src/utils/cloudinaryPresets/formData.js
  src/utils/cloudinaryPresets/restaurantLogo.js
Labels: Restaurant, enhancement

#65 Img restaurant list render
  src/controllers/client.controller.js
  src/models/client.model.js
  src/routes/client.js
  src/utils/cloudinaryPresets/clientImage.js
Labels: Client, enhancement

#66 add conditional auth.js email value
  src/utils/auth.js
Labels: bug
